const charactersTypes = {
    SET_CHARACTERS: '[CHARACTERS] SET_CHARACTERS',
    SET_NEW_CHARACTERS: '[CHARACTERS] SET_NEW_CHARACTERS',
    ADD_NEW_CHARACTER: '[CHARACTERS] ADD_NEW_CHARACTER',
};

export default charactersTypes;
